# Generated by Django 6.0.7 on 2026-07-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chai_varity",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
