# Generated by Django 6.0.7 on 2026-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0002_chai_varity_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chai_varity",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
